import { Place } from "./Place";

export const places: Place[] = [
    {   'id': 1,
        'name': 'Lakeside Motel Warefront',
        'description': 'Reats include a glass of French champagne, parking and a late checkout. Gym included. Flexible cancellation applies',
        'imageUrl': './assets/lakesideMotel.jpg',
        'rating': 4.5,
        'reviewsNumber': 1200,
        'currentPrice': 130,
        'oldPrice': 150,
        'rooms': 1,
        'duration': '2 days',
        'discount': '5% off',
        'promotion': 'Book now and receive 15% off'

    },
    {   'id': 2,
        'name': 'Julia Dens Resort',
        'description': 'Reats include a glass of French champagne, parking and a late checkout. Gym included. Flexible cancellation applies',
        'imageUrl': './assets/juliaDensResort.png',
        'rating': 4.6,
        'reviewsNumber': 1100,
        'currentPrice': 240,
        'rooms': 1,
        'duration': '2 days'
    },
    {   'id': 3,
        'name': 'Aghnim Scepter Hotel',
        'description': 'Reats include a glass of French champagne, parking and a late checkout. Gym included. Flexible cancellation applies',
        'imageUrl': './assets/Aghnim-Scepter-Hotel.jpg',
        'rating': 4.4,
        'reviewsNumber': 1000,
        'currentPrice': 300,
        'rooms': 1,
        'duration': '2 days',
        'promotion': 'Receive 30% discount on a restaurant'
    },
    {   'id': 4,
        'name': 'Marineford Hotel',
        'description': 'Reats include a glass of French champagne, parking and a late checkout. Gym included. Flexible cancellation applies',
        'imageUrl': './assets/Marineford-Hotel.jpg',
        'rating': 4.0,
        'reviewsNumber': 900,
        'currentPrice': 120,
        'rooms': 1,
        'duration': '2 days'
    },
    {   'id': 5,
        'name': 'Shanghai Open House',
        'description': 'Reats include a glass of French champagne, parking and a late checkout. Gym included. Flexible cancellation applies',
        'imageUrl': './assets/Shanghai-Open-House.jpg',
        'rating': 4.9,
        'reviewsNumber': 3200,
        'currentPrice': 145,
        'rooms': 1,
        'duration': '2 days'
    },
    {   'id': 6,
        'name': 'Ocean Waves Resort',
        'description': 'Reats include a glass of French champagne, parking and a late checkout. Gym included. Flexible cancellation applies',
        'imageUrl': './assets/Ocean-Waves-Resort.jpg',
        'rating': 4.5,
        'reviewsNumber': 1200,
        'currentPrice': 310,
        'rooms': 1,
        'duration': '2 days'
    },
    {   'id': 7,
        'name': 'Maimi City frontier',
        'description': 'Reats include a glass of French champagne, parking and a late checkout. Gym included. Flexible cancellation applies',
        'imageUrl': './assets/Maimi-City-frontier.png',
        'rating': 2.0,
        'reviewsNumber': 100,
        'currentPrice': 190,
        'oldPrice': 150,
        'rooms': 1,
        'duration': '2 days',
        'discount': '15% off',
        'promotion': 'Receive 30% discount on a restaurant'
    },
    {   'id': 8,
        'name': 'Oculous Inn Stay',
        'description': 'Reats include a glass of French champagne, parking and a late checkout. Gym included. Flexible cancellation applies',
        'imageUrl': './assets/Oculous-Inn-Stay.png',
        'rating': 3.5,
        'reviewsNumber': 900,
        'currentPrice': 300,
        'oldPrice': 150,
        'rooms': 1,
        'duration': '2 days',
        'discount': '15% off'
    },

]